# version: '3.8'

services:
  streamlit_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1111:8501"
    volumes:
      - .:/app
    # environment:
    #   - STREAMLIT_SERVER_PORT=8501
